### ISSUE TITLE
The difference between paired-end_R2_class2_integration and  paired-end_R2_class1_integration

### ISSUE THREAD

**Issue by xiasijian** [aicb-ZhangLabs/Venus#1]
![image](https://user-images.githubusercontent.com/39158528/224244323-f39f1521-407e-4e7e-9a88-ca51078cfa4d.png)

![image](https://user-images.githubusercontent.com/39158528/224244537-80ccda3c-b31c-4cf7-a915-a79806dd0f2d.png)

**Comment by xiasijian** [comment]
![image](https://user-images.githubusercontent.com/39158528/224245193-d2ef7ee4-549d-4304-9e9d-ed1d80c625ff.png)

**Comment by Cheyujlee** [comment]
Hi @xiasijian ,

Thank you for your interest in our software. Both Class I and Class II integration sites have to have these guide sequences in mind, which are the U5 and U3 of HIV's LTR regions. We added this functionality with HIV in mind from the suggestion of an HIV experimental expert. (You may have to change the guided sequence to your own specific virus.) I have circled the two HIV guided sequence in blue and red below.

The difference between Class I and Class II is that Class I maps to the coding region of a gene while Class II maps to the noncoding region.

Thanks for your interest!
Cheyu.
<img width="1440" alt="Screenshot 2023-03-10 at 1 33 39 PM" src="https://user-images.githubusercontent.com/70779123/224433399-5fe5eb2e-8cbe-48ef-8ada-1b468d473bb6.png">

**Comment by Cheyujlee** [comment]
Closed for now. Answer related to [link](https://github.com/aicb-ZhangLabs/Venus/issues/2#issue-1618786994)
