### ISSUE TITLE
How to prepare the guideFASTA?

### ISSUE THREAD

**Issue by xiasijian** [aicb-ZhangLabs/Venus#2]
![image](https://user-images.githubusercontent.com/39158528/224298576-c2c10b00-a448-45e1-b71f-d80ef54e344a.png)

**Comment by Cheyujlee** [comment]
Hi @xiasijian ,

You would prepare the guideFASTA by looking at which virus you are interested in and obtaining the beginning/ending sequence shown. You can then edit the text files. 

What we have found in the literature is that many software find integration sites that contain some human region and some viral but are simply artifacts. What we did here is have an additional criteria that they need to map to the beginning and the end of the inserted viral sequence (to distinguish from artifacts or not). It would also be a good idea to manually inspect these integration site candidates in IGV afterward. 

<img width="1440" alt="Screenshot 2023-03-10 at 1 33 39 PM" src="https://user-images.githubusercontent.com/70779123/224434162-10cadfd2-75dc-44ef-b276-c58ba69ec5f3.png">
I have attached an example that we did for the HIV virus, confirmed by an experimental expert.

Thanks again!
Cheyu.

**Comment by xiasijian** [comment]
Hi Chenyu
Thanks a lot. I got it! Thank you for your excellent tool.😊

Best wishes,
Sijian Xia
