### ISSUE TITLE
Issue with detection 

### ISSUE THREAD

**Issue by mansisingh2600** [aicb-ZhangLabs/Venus#6]
Hi,

I am trying to run the detection steps for a single-cell RNA file and upon giving the parameters, I get the error that " EXITING because of FATAL ERROR: could not create output file: /home/jupyter/venus/outputs/testing/detection/single-cell/human/Log.out
Check if the path /home/jupyter/venus/outputs/testing/detection/single-cell/human/ exists and you have permissions to write there"

I have a "single-cell" folder that is generated but no "human folder" is created. My repo_dir is set to "repo_dir=/home/jupyter/packages/Venus/outputs" and out_dir is set to "out_dir=/home/jupyter/venus/outputs/testing ". 

This is the error I am facing: 
<img width="1466" alt="Screenshot 2023-08-14 at 2 14 31 PM" src="https://github.com/aicb-ZhangLabs/Venus/assets/140437263/ee3cdbb0-88ae-4281-97f1-8e3273451b79">

Do I need to create a "human" and "virus" folder myself? or should the program do it by itself?

Thanks,

**Comment by Cheyujlee** [comment]
Dear @mansisingh2600 ,

Thank you for your interest and sorry for the 2-week delay! It seems that you have not downloaded the dependency `trim_galore`. The "human" and "virus" folders are created automatically.

Thank you for your interest. Please reply back on this thread for additional Qs.

**Comment by mansisingh2600** [comment]
Hi @Cheyujlee 

Thanks for the guidance, I was able to download "trim-galore" and run the module detection script. However, upon running the fastqs and I tried paired-end and single end fastqs, it keeps running me into this error:

<img width="977" alt="Screenshot 2023-08-28 at 3 58 30 PM" src="https://github.com/aicb-ZhangLabs/Venus/assets/140437263/4ce56316-588b-4ac9-bfc4-3dbe71a2acb4">

It seems like all the errors I am getting relates to not being able to create the 'out' directory and specifically the Log.out file. What would you recommend I do to fix this?

Best,
Mansi
