### ISSUE TITLE
Can venus analyze 10X cellranger data?

### ISSUE THREAD

**Issue by suhuanhou** [aicb-ZhangLabs/Venus#7]
Can venus analyze 10X cellranger data?

Use the bam file or matrix.mtx.gz, features.tsv.gz, barcodes.tsv.gz

**Comment by Cheyujlee** [comment]
Hi @suhuanhou ,

I apologize for the late reply. The bam files might be possible, but this direct alignment would require some heavy changing of the source code.

Perhaps, what would be the fastest option is to convert the BAM into fastq. I reference this website: https://www.metagenomics.wiki/tools/samtools/converting-bam-to-fastq .

**Comment by Cheyujlee** [comment]
Resolved due to inactivity. Sry again for the late response.
