### ISSUE TITLE
detection module test

### ISSUE THREAD

**Issue by antoine4ucsd** [aicb-ZhangLabs/Venus#8]
Hello 
Really nice suite of tools!
I set up my conda env as required and created the index .
files are here
![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/8787221a-4b7d-4833-a918-6396c1009905)

Next I wanted to test on bulk RNAseq with the following cmd
```
python3 ${repo_dir}/src/module-detection/module-detection.py \
    --read ${repo_dir}/test_data/bulk_1.fastq.gz ${repo_dir}/test_data/bulk_2.fastq.gz \
    --virusThreshold 5 \
    --virusChrRef ${repo_dir}/reference_files/virus_chr-ref.tsv \
    --virusGenome ${out_dir}/indices/mega_virus.genomeDir \
    --humanGenome ${out_dir}/indices/human.genomeDir \
    --readFilesCommand zcat \
    --thread 32 \
    --out ${out_dir}/detection/bulk_paired-end


```
results are saved here
![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/f25ec032-b85a-4c14-9215-1d8abdb5ecf1)

but I have NO matches.
I am attaching the log

anything obvious I am missing here?

thank you!

[Log.final.out.txt](https://github.com/user-attachments/files/15596732/Log.final.out.txt)
[v_det-200609.out.txt](https://github.com/user-attachments/files/15596733/v_det-200609.out.txt)

on another note, the barcode link is not working for cellranger (unrelated to this bulk RNAseq analyses)
I used this one instead https://teichlab.github.io/scg_lib_structs/data/10X-Genomics/3M-february-2018.txt.gz

**Comment by Cheyujlee** [comment]
Glad you found a solution!
