### ISSUE TITLE
integration module with toy data

### ISSUE THREAD

**Issue by antoine4ucsd** [aicb-ZhangLabs/Venus#9]
Hello 
I have installed the pipeline as suggested and it seems to run without error.
I get results with the detection module for single cell data and bulk PE RNA seq data

I also tried to run the PE integration module using the code below for the toy dataset
```
#SBATCH --tasks-per-node=64
#SBATCH --mem=128G


python3 ${repo_dir}/src/module-integration/module-integration.py \
    --read ${repo_dir}/test_data/bulk_1.fastq.gz ${repo_dir}/test_data/bulk_2.fastq.gz \
    --virusGenome ${out_dir}/indices/HIV.genomeDir \
    --hybridGenome ${out_dir}/indices/hybrid.genomeDir \
    --guideFASTA ${repo_dir}/reference_files/integrSeq.fna \
    --readFilesCommand zcat \
    --virusChr NC_001802.1 \
    --thread 64 \
    --geneBed ${repo_dir}/reference_files/genes.bed \
    --out ${out_dir}/integration/paired-end
```

but I get no final results / no errors. the log is attached. I suspect a problem with STAR ? only R1 is being generated..

only R1 seems to start
![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/461c2d87-7b0b-4240-883f-7f6a27dcafc4)

but there are still some tmp STAR folder... nothing seems to be aligned?
[joblog.out.txt](https://github.com/user-attachments/files/15650437/joblog.out.txt)
[Log.out.txt](https://github.com/user-attachments/files/15650439/Log.out.txt)

**Comment by Cheyujlee** [comment]
Hi @antoine4ucsd ,

Thanks for your kind words.

Were you able to generate some `tsv` files as shown in screenshot ?
![image](https://github.com/aicb-ZhangLabs/Venus/assets/70779123/5b79de4c-3f1d-4fdf-a504-5f5fbb495a14)

**Comment by antoine4ucsd** [comment]
Hi 
the file are created but empty...
not sure what's wrong here. STAR ?
let me know if you need any other information?

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/67ef32f6-d324-459a-8232-98c8e65d10e7)


but for the toy data, it only creates the R1 folder and not tsv. 

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/3f272e10-d983-4116-bd70-5a929466b8a5)

**Comment by antoine4ucsd** [comment]
see  when I run

```

python3 ${repo_dir}/src/module-integration/module-integration.py \
    --read ${repo_dir}/test_data/bulk_1.fastq.gz ${repo_dir}/test_data/bulk_2.fastq.gz \
    --virusGenome ${out_dir}/indices/HIV.genomeDir \
    --hybridGenome ${out_dir}/indices/hybrid.genomeDir \
    --guideFASTA ${repo_dir}/reference_files/integrSeq.fna \
    --readFilesCommand zcat \
    --virusChr NC_001802.1 \
    --thread 64 \
    --geneBed ${repo_dir}/reference_files/genes.bed \
    --out ${out_dir}/integration/paired-end


```

files being generated are

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/c3ad29d6-964d-4ff4-9ea7-cf081241b38f)
![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/c3ad29d6-964d-4ff4-9ea7-cf081241b38f)


(no R2)

and the log are attached


.out

```
       STAR --runThreadN 64 --outFileNamePrefix /mypath/_venus/Venus/_outputs/integration/paired-end/R1/virus/ --genomeDir /mypath/_venus/Venus/_outputs/indices/HIV.genomeDir --readFilesCommand zcat --readFilesIn /mypath/_venus/Venus/_outputs/integration/paired-end/R1/quality_control/bulk_1_trimmed.fq.gz --outSAMmultNmax 1 --alignIntronMax 1 --winBinNbits 7 --scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0 --scoreDelBase -1 --scoreInsBase -1 --outFilterMultimapNmax -1 --winAnchorMultimapNmax 3000 --seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax 1000 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0 --outFilterScoreMin 27 --outSAMtype BAM Unsorted
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jun 08 09:24:55 ..... started STAR run
Jun 08 09:24:55 ..... loading genome
Jun 08 09:24:55 ..... started mapping
Jun 08 09:26:13 ..... finished mapping
Jun 08 09:26:13 ..... finished successfully
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 26773 reads
        STAR --runThreadN 64 --outFileNamePrefix /mypath/_venus/Venus/_outputs/integration/paired-end/R1/hybrid/ --genomeDir /mypath/_venus/Venus/_outputs/indices/hybrid.genomeDir --readFilesIn /mypath/_venus/Venus/_outputs/integration/paired-end/R1/virus/Aligned.out.fastq --outSAMmultNmax 1 --alignIntronMin 20 --winBinNbits 7 --scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0 --scoreDelBase -1 --scoreInsBase -1 --outFilterMultimapNmax -1 --winAnchorMultimapNmax 3000 --seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax 1000 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0 --outFilterScoreMin 27 --chimOutType WithinBAM SoftClip --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimMultimapNmax 10 --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG 0 --chimNonchimScoreDropMin 10 --alignSJDBoverhangMin 10 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30 --alignInsertionFlush Right --outSAMtype BAM Unsorted
        STAR version: 2.7.9a   compiled: 2021-05-04T09:43:56-0400 vega:/home/dobin/data/STAR/STARcode/STAR.master/source
Jun 08 09:26:14 ..... started STAR run
Jun 08 09:26:14 ..... loading genome
Jun 08 09:26:29 ..... started mapping
samtools sort: failed to read header from "/mypath/_venus/Venus/_outputs/integration/paired-end/R1/hybrid/Aligned.out.bam"
```

[hybrid.Log.out.txt](https://github.com/user-attachments/files/15748939/hybrid.Log.out.txt)
[ven_is-201923.out.txt](https://github.com/user-attachments/files/15748940/ven_is-201923.out.txt)
[virus.Log.final.out.txt](https://github.com/user-attachments/files/15748941/virus.Log.final.out.txt)
[virus.Log.out.txt](https://github.com/user-attachments/files/15748942/virus.Log.out.txt)

maybe this has to do with the STAR or cutadapt settings/version?

and the indices generated look like that

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/18d18d84-9004-416f-9cea-f40de7e12e3a)

**Comment by antoine4ucsd** [comment]
I also tried to run it locally on my mac within the attached env
here there might be a conflict with igzip

files being generated are R1 and R2 but tsv files are empty
https://www.dropbox.com/s/74j22razbsokr81/paired-end.zip?dl=0
[conda.env.txt](https://github.com/user-attachments/files/15748981/conda.env.txt)
[conda.env.txt](https://github.com/user-attachments/files/15748981/conda.env.txt)
[log.test.txt](https://github.com/user-attachments/files/15748982/log.test.txt)
[log.test.txt](https://github.com/user-attachments/files/15748982/log.test.txt)

**Comment by antoine4ucsd** [comment]
on my local install (macOS), I identified a few problems.
first trim_galore version was not called properly -> fixed
second, by default STAR was using --readFilesCommand zcat. I changed it to gunzip -c. 
Despite those changes I still do not get any results 

that does not explain why I do not have any hybrid reads when I run the pipeline on the linux server....

if you have done test on a Mac M1, would you mind sharing the yml so I can install the exact same env?
any thought why I do not get any hybrid when running on my server? seems like a STAR problem too (given the STARtmp folder) - see the log
[hybrid.Log.out.txt](https://github.com/user-attachments/files/15748939/hybrid.Log.out.txt)
[ven_is-201923.out.txt](https://github.com/user-attachments/files/15748940/ven_is-201923.out.txt)
[virus.Log.final.out.txt](https://github.com/user-attachments/files/15748941/virus.Log.final.out.txt)
[virus.Log.out.txt](https://github.com/user-attachments/files/15748942/virus.Log.out.txt)

**Comment by Cheyujlee** [comment]
Good morning @antoine4ucsd ,

I have tried it before on my M1 with the following yml file.

I would montior the memory usage with the app `activity monitor` however to see whether memory requirements are sufficient (mapping usually takes lots of GB ram).
[venus_M1.yml.txt](https://github.com/user-attachments/files/15752701/venus_M1.yml.txt)

**Comment by antoine4ucsd** [comment]
thank you
I still don't get why I don't get any results on my server. no hybrids... I wonder if it has to do with the indices generated (no errors...)?
do you have your own indices saved so I can try ?
other possible explanations?
meanwhile. I will try with your new env on my mac 
thank you!

**Comment by antoine4ucsd** [comment]
unfortunately the yml file is not working (many packages conflicts)

**Comment by antoine4ucsd** [comment]
on my server, STAR 2.7.9a is called
I do get align.bam for viruses 

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/8cdd6a2c-f0b7-4da5-b28c-8d55b75de510)


but nothing for hybrid

![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/2f29e714-bddc-4482-8188-553bcd5748c5)


the cmd line called is
```
 STAR --runThreadN 64 --outFileNamePrefix /mypath/_venus/Venus/_outputs/integration/paired-end/R1/hybrid/ --genomeDir /mypath/_venus/Venus/_outputs/indices/hybrid.genomeDir --readFilesIn /mypath/_venus/Venus/_outputs/integration/paired-end/R1/virus/Aligned.out.fastq --outSAMmultNmax 1 --alignIntronMin 20 --winBinNbits 7 --scoreGenomicLengthLog2scale 0 --scoreDelOpen 0 --scoreInsOpen 0 --scoreDelBase -1 --scoreInsBase -1 --outFilterMultimapNmax -1 --winAnchorMultimapNmax 3000 --seedPerReadNmax 30000 --alignWindowsPerReadNmax 30000 --seedPerWindowNmax 1000 --outFilterMatchNminOverLread 0 --outFilterScoreMinOverLread 0 --outFilterScoreMin 27 --chimOutType WithinBAM SoftClip --chimSegmentMin 12 --chimJunctionOverhangMin 8 --chimMultimapNmax 10 --chimMultimapScoreRange 3 --chimScoreJunctionNonGTAG 0 --chimNonchimScoreDropMin 10 --alignSJDBoverhangMin 10 --alignIntronMax 100000 --alignSJstitchMismatchNmax 5 -1 5 5 --alignSplicedMateMapLminOverLmate 0 --alignSplicedMateMapLmin 30 --alignInsertionFlush Right --outSAMtype BAM Unsorted
```


within the junction subfolder I have those
![image](https://github.com/aicb-ZhangLabs/Venus/assets/18502631/229797b3-c21a-41d2-8226-47695885fdc1)


attaching the full log
I have no preference running it on my server or locally on my Mac but neither of those work for me at the moment
not sure what to try next...


[ven_is-201944.out.txt](https://github.com/user-attachments/files/15753307/ven_is-201944.out.txt)

**Comment by antoine4ucsd** [comment]
trying again locally
I had to switch from zcat to gunzip 
still not working
```
	STAR version: 2.7.11b   compiled:  :/Users/distiller/project/STARcompile/source
Jun 09 11:47:32 ..... started STAR run
Jun 09 11:47:32 ..... loading genome
Jun 09 11:47:32 ..... started mapping
gunzip: error writing to output: Broken pipe

```

so I modified the STAR parameters and reduced  --seedPerWindowNmax  to 100 (instead of 1000)
in that case, it seems to run without error but the tsv output are still empty
all results and logs are here
https://www.dropbox.com/scl/fo/myis7wdkf08b9pw4u4l3f/APPekXz8y4ISapd2CZ604aA?rlkey=fm5ewtxt036to62hh1v1pkrdr&dl=0

**Comment by antoine4ucsd** [comment]
important update when running on my server (linux)
I was finally able to generate the SAME results BUT I had to modify the module integration with --seedPerWindowNmax 100. 
Despite allocating
```
#SBATCH --tasks-per-node=112
#SBATCH --mem=224G

and --thread 112 
```
STAR process was killed...
now it works for the toy dataset!!!
next is to try it on real data... which are much bigger.
will keep you posted

**Comment by Cheyujlee** [comment]
Resolved.
